import type { Metadata } from "next";
import "./globals.css";
import MainContainer from "./components/layout/MainContainer";
import {CratProvider} from './context/CartContext'

export const metadata: Metadata = {
  title: "itemdev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <CratProvider>
          <MainContainer>
              {children}

          </MainContainer>
        </CratProvider>
      </body>
    </html>
  );
}
